sudo: false

language: c

cache:
  apt: true
  directories:
    - $HOME/.stack/

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
  # Install stack
  - mkdir -p $HOME/.local/bin $HOME/.local/include $HOME/.local/lib
  - export PATH=~/.local/bin:$PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
  # Install libstatgrab
  - travis_retry wget http://dl.ambiweb.de/mirrors/ftp.i-scream.org/libstatgrab/libstatgrab-0.90.tar.gz
  - tar xvf libstatgrab-0.90.tar.gz
  - (cd libstatgrab-0.90/ && ./configure --prefix=$HOME/.local/ && make && make install)

install:
  - cat .travis/stack.yaml >> stack.yaml
  - stack update
  - stack setup
  - stack install hlint
  - stack build skylark-core --only-dependencies

before_script:
  # Download AWS cli
  - pip install --user --upgrade awscli
  # Download local DynamoDB
  - mkdir -p .dynamo
  - pushd .dynamo
  - travis_retry curl -L -o latest-dynamo.tar.gz http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
  - tar -zxvf latest-dynamo.tar.gz
  - popd

script:
  - make lint
  - AWS_SECRET_ACCESS_KEY=foo AWS_ACCESS_KEY_ID=bar stack build skylark-core --test
